// client/src/pages/Register.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../contexts/AuthContext';

export default function Register() {
  const { t } = useTranslation();
  const { register } = useAuth();
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await register(email, password, name);
      navigate('/dashboard');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            {t('auth.registerTitle')}
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <p className="text-sm text-red-800">{error}</p>
            </div>
          )}
          <div className="rounded-md shadow-sm -space-y-px">
            <div>
              <label htmlFor="name" className="sr-only">
                {t('auth.name')}
              </label>
              <input
                id="name"
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                placeholder={t('auth.name')}
              />
            </div>
            <div>
              <label htmlFor="email" className="sr-only">
                {t('auth.email')}
              </label>
              <input
                id="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                placeholder={t('auth.email')}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">
                {t('auth.password')}
              </label>
              <input
                id="password"
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                placeholder={t('auth.password')}
              />
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={loading}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50"
            >
              {loading ? t('common.loading') : t('auth.register')}
            </button>
          </div>
        </form>
        <div className="text-center">
          <p className="text-sm text-gray-600">
            {t('auth.hasAccount')}{' '}
            <Link to="/login" className="font-medium text-primary-600 hover:text-primary-500">
              {t('auth.login')}
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

// client/src/routes/auth/register/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { register } from '$lib/auth/register';
    import FormInput from '$lib/components/FormInput.svelte';
    import { APP_NAME } from '$lib/config';

    let email = $state('');
    let name = $state('');
    let password = $state('');
    let passwordConfirm = $state('');
    let error = $state('');
    let loading = $state(false);

    async function handleSubmit() {
        if (password !== passwordConfirm) {
            error = 'Passwords do not match';
            return;
        }
        
        loading = true;
        error = '';
        
        const result = await register(email, password, name);
        
        if (result.success) {
            goto('/');
        } else {
            error = result.error ?? 'Registration failed';
        }
        loading = false;
    }
</script>

<svelte:head>
    <title>Register | {APP_NAME}</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-gray-50">
    <div class="w-full max-w-sm space-y-6 rounded-lg bg-white p-8 shadow">
        <h1 class="text-2xl font-bold">Create account</h1>
        
        {#if error}
            <p class="rounded bg-red-100 p-3 text-red-700">{error}</p>
        {/if}
        
        <form onsubmit={handleSubmit} class="space-y-4">
            <FormInput id="email" label="Email" type="email" bind:value={email} />
            <FormInput id="name" label="Name" type="text" bind:value={name} />
            <FormInput id="password" label="Password" type="password" bind:value={password} />
            <FormInput id="passwordConfirm" label="Confirm Password" type="password" bind:value={passwordConfirm} />
            
            <button
                type="submit"
                disabled={loading}
                class="w-full rounded bg-blue-600 py-2 text-white hover:bg-blue-700 disabled:opacity-50"
            >
                {loading ? 'Creating...' : 'Register'}
            </button>
        </form>
        
        <p class="text-center text-sm">
            Have an account? <a href="/auth/login" class="text-blue-600 hover:underline">Sign in</a>
        </p>
    </div>
</div>
